version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 80:80
    networks:
      - net
    links:
      - database
    deploy:
      mode:
        replicated
      replicas: 6
    volumes:
      - wiki_img:/var/www/html/images
      - ./logo.jpeg:/var/www/html/images/logo.jpeg
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php
      # Extensions
      # - ./extensions/MobileFrontend:/var/www/html/extensions/MobileFrontend
      # - ./extensions/Moderation:/var/www/html/extensions/Moderation
      # - ./extensions/NotebookViewer:/var/www/html/extensions/NotebookViewer
  database:
    networks:
      - net
    image: mariadb
    volumes:
      - db_vol:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
  visualizer:
      image: dockersamples/visualizer:stable
      ports:
        - "1337:8080"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      deploy:
        placement:
          constraints: [node.role == manager]
      networks:
        - net
networks:
  net:
volumes:
  db_vol:
  wiki_img:
